### ISSUE TITLE
Maybe not python 3.9 compliant

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/mosaic#17]
On conda-forge, we're seeing:
```
import: 'mosaic'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/mosaic_1731025142822/test_tmp/run_test.py", line 2, in <module>
    import mosaic
  File "/home/conda/feedstock_root/build_artifacts/mosaic_1731025142822/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.9/site-packages/mosaic/__init__.py", line 1, in <module>
    from mosaic import datasets
  File "/home/conda/feedstock_root/build_artifacts/mosaic_1731025142822/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.9/site-packages/mosaic/datasets.py", line 46, in <module>
    cache_dir: None | str | os.PathLike = None,
TypeError: unsupported operand type(s) for |: 'NoneType' and 'type'
```

**Comment by xylar** [comment]
I believe the fix is to add `typing_extensions` as a dependency.  It could just be a dependency for python 3.9 but I believe it's just an empty metapackage for higher python versions so it doesn't matter.

**Comment by xylar** [comment]
No, that didn't work.

If you see here:
https://stackoverflow.com/questions/76712720/typeerror-unsupported-operand-types-for-type-and-nonetype

It seems like the `|` syntax just can't be made to work in python 3.9 and a clunkier `Union[]` interface is required.

My suggestion would be to keep things as they are and just not support python 3.9.

**Comment by andrewdnolan** [comment]
Thanks for hunting that down, @Xylar! 

I agree that keeping the `|` syntax seems worth it enough to drop python 3.9 support. 

I see that you've constrained the min python version to 3.10 in the `meta.yml` on conda-forge.  For constraining the `pyproject.toml`, should I release a patch version or is the existing release OK for conda forge even tough the constrained python versions are different in the `meta.yml` and the `pyproject.toml` files?

**Comment by xylar** [comment]
No need for a patch release.

**Comment by andrewdnolan** [comment]
Sounds good! Thanks for your help with all this.
